#!/usr/bin/with-contenv bash
# vim: ft=sh
# shellcheck shell=bash

set -o errexit
set -o pipefail

# shellcheck source=root/app/lib.sh
source "/app/lib.sh"

wait_service "provider"

_term() {
	infof "Caught SIGTERM signal!"
	wg-quick down wg0
}

trap _term SIGTERM

if [[ -f "${WG_CONFIG:?}.noconn" ]]; then
	warnf "Skipping wg-quick connection (already connected via provider)"
else
	infof "Connecting ..."

	wg-quick up wg0
fi

infof "Connected!"
notify_startup
wait_forever
