#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -o errexit
set -o pipefail

# shellcheck source=../../../app/lib.sh
source "/app/lib.sh"

wait_service "provider"

_term() {
	infof "Caught SIGTERM signal!"
	wg-quick down wg0
}

trap _term SIGTERM

infof "Connecting ..."

wg-quick up wg0

infof "Connected!"

notify_startup

wait_forever
