#!/usr/bin/with-contenv bash
# vim: ft=sh
# shellcheck shell=bash

set -o errexit
set -o pipefail

# shellcheck source=root/app/lib.sh
source "/app/lib.sh"

readiness="$1"

_term() {
	infof "Caught SIGTERM signal!"
	exit 0
}

trap _term SIGTERM

if [[ -n "$readiness" ]]; then
	notify_startup
fi

wait_forever
