#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -o pipefail

# shellcheck source=../../lib.sh
source "/app/lib.sh"

wait_service "nordvpn" || exit $?

WG_CONFIG="${1:?}"
CREDENTIALS_FILE="${CONFIG_DIR:?}/providers/nordvpn/credentials.txt"
IFACE="nordlynx"

random_region() {
	nordvpn countries |
		sed -re 's/, /\n/g' |
		shuf -n 1
}

gen_wg_config() {
	local username="${1:?}"
	local password="${2:?}"
	local region="${3:?}"
	local output="${4:?}"

	nordvpn set technology "nordlynx" ||
		return $?

	nordvpn logout >/dev/null

	nordvpn login --legacy --username "$username" --password "$password" ||
		return $?

	local connect_args=()

	if [[ "$region" != "best" ]]; then
		connect_args+=("$region")
	fi

	nordvpn connect "${connect_args[@]}" ||
		return $?

	local cidr

	cidr="$(ip -br addr show dev "$IFACE" | awk '{print $3}')" ||
		return $?

	wg showconf "$IFACE" |
		sed -re "/^\[Interface\]/ a Address = ${cidr}" >"$output" ||
		return $?

	nordvpn disconnect ||
		return $?

	chmod 600 "$output"
}

main() {
	local username="$NORDVPN_USERNAME"
	local password="$NORDVPN_PASSWORD"
	local region="$NORDVPN_REGION"

	if [[ -n "$username" && -n "$password" ]]; then
		write_credentials "$username" "$password" "$CREDENTIALS_FILE" ||
			fatalw "Failed to write wireguard credentials. Fix the issues and restart the container"
	else
		if [[ -r "$CREDENTIALS_FILE" ]]; then
			local -A credentials

			read_credentials "$CREDENTIALS_FILE" credentials ||
				fatalf "Failed to read credentials from %s" "$CREDENTIALS_FILE"

			username="${credentials["username"]}"
			password="${credentials["password"]}"
		fi
	fi

	if [[ -z "$username" || -z "$password" ]]; then
		fatalw "NORDVPN_USERNAME or NORDVPN_PASSWORD is not set. Configure these environment variables and restart the container"
	fi

	if [[ -z "$region" ]]; then
		region="best"
	fi

	if [[ "$region" == "random" ]]; then
		infof "Selecting random region"

		region="$(random_region)" ||
			fatalf "Failed to select random region"
	fi

	infof "Selected region: %s" "${region@Q}"

	gen_wg_config "$username" "$password" "$region" "$WG_CONFIG" ||
		fatalw "Failed to generate wireguard config. Fix the issues and restart the container"
}

main
