#!/usr/bin/with-contenv bash
# vim: ft=sh
# shellcheck shell=bash

set -o errexit
set -o pipefail

# shellcheck source=root/app/lib.sh
source "/app/lib.sh"

wait_service "wireguard"

SETTINGS_FILE="${TRANSMISSION_HOME:?}/settings.json"

if [[ ! -f "$SETTINGS_FILE" ]]; then
	fatalf "Transmission configuration not found at %s" "${SETTINGS_FILE@Q}"
fi

if [[ -n "$TRANSMISSION_WEB_UI" ]]; then
	web_ui_path="${TRANSMISSION_WEB_PREFIX:?}/$TRANSMISSION_WEB_UI"

	if [[ -d "$web_ui_path" ]]; then
		infof "Using web UI: %s" "${TRANSMISSION_WEB_UI@Q}"

		export TRANSMISSION_WEB_HOME="$web_ui_path"
	else
		warnf "Web UI not found: %s" "${TRANSMISSION_WEB_UI@Q}"
	fi
fi

options=(
	"--foreground"
	"--config-dir" "${TRANSMISSION_HOME:?}"
)

log_file=""

case "$TRANSMISSION_LOG" in
"stdout")
	log_file="/dev/stdout"
	;;
"default")
	log_file="${TRANSMISSION_HOME:?}/transmission.log"
	;;
?*)
	log_file="$TRANSMISSION_LOG"
	;;
esac

if [[ -n "$log_file" ]]; then
	options+=("--logfile" "$log_file")
fi

infof "Starting Transmission"

exec s6-setuidgid "abc" \
	"transmission-daemon" "${options[@]}"
