#!/usr/bin/with-contenv bash
# vim: ft=sh
# shellcheck shell=bash
# Based on https://github.com/haugene/docker-transmission-openvpn/blob/d7e7a24fbb384df866c2e9ae0e31104895dd26ea/transmission/start.sh

set -o errexit
set -o pipefail

# shellcheck source=root/app/lib.sh
source "/app/lib.sh"

wait_service "wireguard"

SETTINGS_FILE="${TRANSMISSION_HOME:?}/settings.json"

if [[ ! -f "$SETTINGS_FILE" ]]; then
	fatalf "Transmission configuration not found at %s" "$SETTINGS_FILE"
fi

WEB_UI_PREFIX="/opt/transmission-ui"

if [[ -n "$TRANSMISSION_WEB_UI" ]]; then
	WEB_UI_PATH="$WEB_UI_PREFIX/$TRANSMISSION_WEB_UI"

	if [[ -d "$WEB_UI_PATH" ]]; then
		infof "Using web UI: %s" "$TRANSMISSION_WEB_UI"
		export TRANSMISSION_WEB_HOME="$WEB_UI_PATH"
	fi
fi

options=(
	"--foreground"
	"--config-dir" "${TRANSMISSION_HOME:?}"
)

log_file=""

case "$TRANSMISSION_LOG" in
"stdout")
	log_file="/dev/stdout"
	;;
"default")
	log_file="$TRANSMISSION_HOME/transmission.log"
	;;
?*)
	log_file="$TRANSMISSION_LOG"
	;;
esac

if [[ -n "$log_file" ]]; then
	options+=("--logfile" "$log_file")
fi

infof "Starting Transmission"

exec s6-setuidgid "abc" \
	"transmission-daemon" "${options[@]}"
