#!/usr/bin/with-contenv bash
# shellcheck shell=bash

set -o pipefail

WG_CONFIG="/config/wg0.conf"

if [[ -z "$PROVIDER" ]]; then
	echo >&2 "**** PROVIDER is not set. Configure it and restart the container ****"
	sleep infinity
fi

echo "**** Selected provider: $PROVIDER ****"

provider_dir="/app/providers/${PROVIDER}"
gen_config="${provider_dir}/gen_config"

if [[ ! -x "$gen_config" ]]; then
	echo >&2 "**** Provider ${PROVIDER} doesn't provide a gen_config script. THIS IS A BUG! ****"
	sleep infinity
fi

if ! "$gen_config" "$WG_CONFIG"; then
	echo >&2 "**** Provider ${PROVIDER} failed to generate an wireguard config ****"
	echo >&2 "**** Fix the issues and restart the container ****"
	sleep infinity
fi
