#!/usr/bin/with-contenv bash
# vim: ft=sh
# shellcheck shell=bash

set -o errexit
set -o pipefail

if [[ -z "$LOCAL_NETWORK" ]]; then
	warnf "Skipping local network configuration"
	exit 0
fi

# shellcheck source=root/app/lib.sh
source "/app/lib.sh"

default_route() {
	local route addr_iface iface addr

	route="$(ip route list match 0.0.0.0)" || return $?
	addr_iface="$(awk '{ if ($5 != "tun0") { print $5 ";" $3; exit } }' <<<"$route")" || return $?
	iface="$(echo "$addr_iface" | cut -d ";" -f1)" || return $?
	addr="$(echo "$addr_iface" | cut -d ";" -f2)" || return $?

	echo "$iface"
	echo "$addr"
}

# shellcheck disable=2310,2311
route_s="$(default_route)" || {
	fatalf "Could not find default route, skipping local network configuration"
}

route=()

readarray -t route <<<"$route_s"

gw_iface="${route[0]}"
gw_addr="${route[1]}"
networks=()

readarray -t -d ',' networks < <(echo -n "$LOCAL_NETWORK")

for net in "${networks[@]}"; do
	infof "Adding route to local network %s via %s dev %s" "$net" "$gw_addr" "$gw_iface"

	ip route add "$net" via "$gw_addr" dev "$gw_iface" ||
		fatalf "Failed to add route, exiting"
done
